# Generated by Django 5.2.8 on 2025-11-22 14:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_lesson_student_lesson_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Стоимость занятия (за одного ученика)'),
        ),
    ]
