# Generated by Django 5.2.8 on 2025-11-22 14:37

import django.db.models.deletion
from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def ensure_all_have_tutor(apps, schema_editor):
    """Убеждаемся, что все записи имеют репетитора перед изменением полей"""
    Tutor = apps.get_model('main', 'Tutor')
    Student = apps.get_model('main', 'Student')
    Lesson = apps.get_model('main', 'Lesson')
    
    # Получаем первого репетитора
    tutor = Tutor.objects.first()
    if not tutor:
        # Если нет репетиторов, создаем дефолтного
        User = apps.get_model('auth', 'User')
        
        default_user, created = User.objects.get_or_create(
            username='default_tutor',
            defaults={
                'first_name': 'Default',
                'last_name': 'Tutor',
                'email': 'default@tutor.com',
                'is_active': True,
                'password': make_password('changeme123'),
            }
        )
        tutor = Tutor.objects.create(user=default_user)
    
    # Назначаем репетитора всем записям без репетитора
    Student.objects.filter(tutor__isnull=True).update(tutor=tutor)
    Lesson.objects.filter(tutor__isnull=True).update(tutor=tutor)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20251122_1731'),
    ]

    operations = [
        migrations.RunPython(ensure_all_have_tutor),
        migrations.AlterField(
            model_name='lesson',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.tutor', verbose_name='Репетитор'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.tutor', verbose_name='Репетитор'),
        ),
    ]
