# Generated by Django 5.2.8 on 2025-11-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lesson_tutor_alter_student_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
