# Generated by Django 5.2.8 on 2025-11-27 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.tutor', verbose_name='Репетитор')),
            ],
            options={
                'verbose_name': 'Группа учеников',
                'verbose_name_plural': 'Группы учеников',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='students', to='main.studentgroup', verbose_name='Группы'),
        ),
    ]
