# Generated by Django 5.2.8 on 2025-12-01 09:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentgroup_student_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_balance_payment',
            field=models.BooleanField(default=False, verbose_name='Оплата с предоплаты'),
        ),
        migrations.AddField(
            model_name='student',
            name='prepaid_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Баланс предоплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('transfer', 'Перевод'), ('balance', 'Списано с предоплаты')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
