# Generated by Django 5.2.8 on 2026-04-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_payment_is_balance_payment_student_prepaid_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена по умолчанию'),
        ),
    ]
