# Generated by Django 5.2.8 on 2026-05-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_add_default_price_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cancellation_note',
            field=models.TextField(blank=True, verbose_name='Заметка об отмене'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('air_alert', 'Воздушная тревога / атака БПЛ'), ('student_sick', 'Ученик заболел'), ('tutor_sick', 'Репетитор заболел'), ('student_request', 'Просьба ученика'), ('rescheduled', 'Перенос'), ('other', 'Другое')], max_length=30, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('cancelled', 'Отменено')], default='scheduled', max_length=20, verbose_name='Статус'),
        ),
    ]
